.Dd January 15 2024
.Dt U8GLEN 3
.Os
.Sh NAME
.Nm u8glen
.Nd count Unicode graphemes
.Sh LIBRARY
.Lb librune
.Sh SYNOPSIS
.In gbrk.h
.Ft size_t
.Fn u8glen "const char8_t *s" "size_t n"
.Sh DESCRIPTION
The
.Fn u8glen
function returns the number of UTF-8 encoded Unicode graphemes in the
buffer
.Fa s
of length
.Fa n
bytes.
.Pp
This function assumes that
.Fa s
contains only valid UTF-8.
.Sh RETURN VALUES
The
.Fn u8glen
function returns the number of graphemes in the buffer
.Fa s .
.Sh EXAMPLES
The following call to
.Fn u8glen
will return 6 while the call to
.Fn u8len
will return 7 as a result of user-preceived characters such as
.Sq е́
taking up multiple codepoints.
.Bd -literal -offset indent
char8_t s[] = u8\(dqПриве́т\(dq;
size_t cplen, glen;

cplen = u8len(s, sizeof(s) - 1);
glen = u8glen(s, sizeof(s) - 1);
.Ed
.Sh SEE ALSO
.Xr u8len 3 ,
.Xr u8wdth 3 ,
.Xr unicode 7 ,
.Xr utf\-8 7
.Sh STANDARDS
.Rs
.%A F. Yergeau
.%D November 2003
.%R RFC 3629
.%T UTF-8, a transformation format of ISO 10646
.Re
.Pp
.Lk https://www.unicode.org/versions/Unicode15.1.0/ \
"The Unicode\(rg Standard Version 15.1.0"
.Sh AUTHORS
.An Thomas Voss Aq Mt mail@thomasvoss.com
