/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"
#include "rune.h"

#include "internal/bitset.h"
#include "internal/common.h"

/* clang-format off */

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{RUNE_C(0x000E40), RUNE_C(0x000E44)},
	{RUNE_C(0x000EC0), RUNE_C(0x000EC4)},
	{RUNE_C(0x0019B5), RUNE_C(0x0019B7)},
	{RUNE_C(0x0019BA), RUNE_C(0x0019BA)},
	{RUNE_C(0x00AAB5), RUNE_C(0x00AAB6)},
	{RUNE_C(0x00AAB9), RUNE_C(0x00AAB9)},
	{RUNE_C(0x00AABB), RUNE_C(0x00AABC)},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rprop_is_loe(rune ch)
{
	return lookup(ch);
}
