/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"

#include "internal/common.h"

/* clang-format off */

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{0x002202, 0x002202},
	{0x002207, 0x002207},
	{0x00221E, 0x00221E},
	{0x01D6C1, 0x01D6C1},
	{0x01D6DB, 0x01D6DB},
	{0x01D6FB, 0x01D6FB},
	{0x01D715, 0x01D715},
	{0x01D735, 0x01D735},
	{0x01D74F, 0x01D74F},
	{0x01D76F, 0x01D76F},
	{0x01D789, 0x01D789},
	{0x01D7A9, 0x01D7A9},
	{0x01D7C3, 0x01D7C3},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rune_has_prop_id_compat_math_start(rune ch)
{
	return lookup(ch);
}
