/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"
#include "rune.h"

#include "internal/bitset.h"

/* clang-format off */

static const uint64_t bitset[] = {
	UINT64_C(0xFC00FFFE00000000),
	UINT64_C(0x7800000178000001),
	UINT64_C(0x88435AFE00000000),
	UINT64_C(0x0080000000800000),
};

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{RUNE_C(0x002010), RUNE_C(0x002027)},
	{RUNE_C(0x002030), RUNE_C(0x00203E)},
	{RUNE_C(0x002041), RUNE_C(0x002053)},
	{RUNE_C(0x002055), RUNE_C(0x00205E)},
	{RUNE_C(0x002190), RUNE_C(0x00245F)},
	{RUNE_C(0x002500), RUNE_C(0x002775)},
	{RUNE_C(0x002794), RUNE_C(0x002BFF)},
	{RUNE_C(0x002E00), RUNE_C(0x002E7F)},
	{RUNE_C(0x003001), RUNE_C(0x003003)},
	{RUNE_C(0x003008), RUNE_C(0x003020)},
	{RUNE_C(0x003030), RUNE_C(0x003030)},
	{RUNE_C(0x00FD3E), RUNE_C(0x00FD3F)},
	{RUNE_C(0x00FE45), RUNE_C(0x00FE46)},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rprop_is_pat_syn(rune ch)
{
	return ch <= LATIN1_MAX ? BSCHK(bitset, ch) : lookup(ch);
}
