/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"

#include "internal/common.h"

/* clang-format off */

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{0x01F3FB, 0x01F3FF},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rprop_emoji_modifier(rune ch)
{
	return lookup(ch);
}
