/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"
#include "rune.h"

#include "internal/common.h"

/* clang-format off */

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{RUNE_C(0x002202), RUNE_C(0x002202)},
	{RUNE_C(0x002207), RUNE_C(0x002207)},
	{RUNE_C(0x00221E), RUNE_C(0x00221E)},
	{RUNE_C(0x01D6C1), RUNE_C(0x01D6C1)},
	{RUNE_C(0x01D6DB), RUNE_C(0x01D6DB)},
	{RUNE_C(0x01D6FB), RUNE_C(0x01D6FB)},
	{RUNE_C(0x01D715), RUNE_C(0x01D715)},
	{RUNE_C(0x01D735), RUNE_C(0x01D735)},
	{RUNE_C(0x01D74F), RUNE_C(0x01D74F)},
	{RUNE_C(0x01D76F), RUNE_C(0x01D76F)},
	{RUNE_C(0x01D789), RUNE_C(0x01D789)},
	{RUNE_C(0x01D7A9), RUNE_C(0x01D7A9)},
	{RUNE_C(0x01D7C3), RUNE_C(0x01D7C3)},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rprop_is_id_compat_math_start(rune ch)
{
	return lookup(ch);
}
