/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"
#include "rune.h"

#include "internal/bitset.h"
#include "internal/common.h"

/* clang-format off */

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{RUNE_C(0x002FF0), RUNE_C(0x002FF1)},
	{RUNE_C(0x002FF4), RUNE_C(0x002FFD)},
	{RUNE_C(0x0031EF), RUNE_C(0x0031EF)},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rprop_is_idbo(rune ch)
{
	return lookup(ch);
}
