/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"

#include "internal/common.h"

/* clang-format off */

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{0x00180B, 0x00180D},
	{0x00180F, 0x00180F},
	{0x00FE00, 0x00FE0F},
	{0x0E0100, 0x0E01EF},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rprop_variation_selector(rune ch)
{
	return lookup(ch);
}
