/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"
#include "rune.h"

#include "internal/bitset.h"

/* clang-format off */

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{RUNE_C(0x000600), RUNE_C(0x000605)},
	{RUNE_C(0x0006DD), RUNE_C(0x0006DD)},
	{RUNE_C(0x00070F), RUNE_C(0x00070F)},
	{RUNE_C(0x000890), RUNE_C(0x000891)},
	{RUNE_C(0x0008E2), RUNE_C(0x0008E2)},
	{RUNE_C(0x0110BD), RUNE_C(0x0110BD)},
	{RUNE_C(0x0110CD), RUNE_C(0x0110CD)},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rprop_is_pcm(rune ch)
{
	return lookup(ch);
}
