/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"
#include "rune.h"

#include "internal/common.h"

/* clang-format off */

#if BIT_LOOKUP
static const unsigned _BitInt(LATIN1_MAX + 1) mask =
	0x008000000080000088435AFE000000007800000178000001FC00FFFE00000000uwb;
#endif

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{RUNE_C(0x000021), RUNE_C(0x00002F)},
	{RUNE_C(0x00003A), RUNE_C(0x000040)},
	{RUNE_C(0x00005B), RUNE_C(0x00005E)},
	{RUNE_C(0x000060), RUNE_C(0x000060)},
	{RUNE_C(0x00007B), RUNE_C(0x00007E)},
	{RUNE_C(0x0000A1), RUNE_C(0x0000A7)},
	{RUNE_C(0x0000A9), RUNE_C(0x0000A9)},
	{RUNE_C(0x0000AB), RUNE_C(0x0000AC)},
	{RUNE_C(0x0000AE), RUNE_C(0x0000AE)},
	{RUNE_C(0x0000B0), RUNE_C(0x0000B1)},
	{RUNE_C(0x0000B6), RUNE_C(0x0000B6)},
	{RUNE_C(0x0000BB), RUNE_C(0x0000BB)},
	{RUNE_C(0x0000BF), RUNE_C(0x0000BF)},
	{RUNE_C(0x0000D7), RUNE_C(0x0000D7)},
	{RUNE_C(0x0000F7), RUNE_C(0x0000F7)},
	{RUNE_C(0x002010), RUNE_C(0x002027)},
	{RUNE_C(0x002030), RUNE_C(0x00203E)},
	{RUNE_C(0x002041), RUNE_C(0x002053)},
	{RUNE_C(0x002055), RUNE_C(0x00205E)},
	{RUNE_C(0x002190), RUNE_C(0x00245F)},
	{RUNE_C(0x002500), RUNE_C(0x002775)},
	{RUNE_C(0x002794), RUNE_C(0x002BFF)},
	{RUNE_C(0x002E00), RUNE_C(0x002E7F)},
	{RUNE_C(0x003001), RUNE_C(0x003003)},
	{RUNE_C(0x003008), RUNE_C(0x003020)},
	{RUNE_C(0x003030), RUNE_C(0x003030)},
	{RUNE_C(0x00FD3E), RUNE_C(0x00FD3F)},
	{RUNE_C(0x00FE45), RUNE_C(0x00FE46)},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rprop_is_pat_syn(rune ch)
{
	return
#if BIT_LOOKUP
		ch <= LATIN1_MAX ? (mask & (1 << ch)) :
#endif
		lookup(ch);
}
