/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"

#include "internal/common.h"

/* clang-format off */

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{0x000E40, 0x000E44},
	{0x000EC0, 0x000EC4},
	{0x0019B5, 0x0019B7},
	{0x0019BA, 0x0019BA},
	{0x00AAB5, 0x00AAB6},
	{0x00AAB9, 0x00AAB9},
	{0x00AABB, 0x00AABC},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rprop_is_loe(rune ch)
{
	return lookup(ch);
}
