/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"
#include "rune.h"

#include "internal/bitset.h"
#include "internal/common.h"

/* clang-format off */

static const uint64_t bitset[] = {
	UINT64_C(0x0000000100003E00),
	UINT64_C(0x0000000000000000),
	UINT64_C(0x0000000100000020),
	UINT64_C(0x0000000000000000),
};

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{RUNE_C(0x001680), RUNE_C(0x001680)},
	{RUNE_C(0x002000), RUNE_C(0x00200A)},
	{RUNE_C(0x002028), RUNE_C(0x002029)},
	{RUNE_C(0x00202F), RUNE_C(0x00202F)},
	{RUNE_C(0x00205F), RUNE_C(0x00205F)},
	{RUNE_C(0x003000), RUNE_C(0x003000)},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rprop_is_wspace(rune ch)
{
	return ch <= LATIN1_MAX ? BSCHK(bitset, ch) : lookup(ch);
}
