/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"
#include "rune.h"

#include "internal/bitset.h"
#include "internal/common.h"

/* clang-format off */

static const uint64_t bitset[] = {
	UINT64_C(0x03FF000000000000),
	UINT64_C(0x0000007E0000007E),
	UINT64_C(0x0000000000000000),
	UINT64_C(0x0000000000000000),
};

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{RUNE_C(0x00FF10), RUNE_C(0x00FF19)},
	{RUNE_C(0x00FF21), RUNE_C(0x00FF26)},
	{RUNE_C(0x00FF41), RUNE_C(0x00FF46)},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rprop_is_hex(rune ch)
{
	return ch <= LATIN1_MAX ? BSCHK(bitset, ch) : lookup(ch);
}
