/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"

#include "internal/common.h"

/* clang-format off */

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{0x00061C, 0x00061C},
	{0x00200E, 0x00200F},
	{0x00202A, 0x00202E},
	{0x002066, 0x002069},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rprop_bidi_control(rune ch)
{
	return lookup(ch);
}
