/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"
#include "rune.h"

#include "internal/bitset.h"

/* clang-format off */

static const uint64_t bitset[] = {
	UINT64_C(0x0000000000000000),
	UINT64_C(0x0000000000000000),
	UINT64_C(0x020C000000000000),
	UINT64_C(0x0000000000000000),
};

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{RUNE_C(0x002070), RUNE_C(0x002070)},
	{RUNE_C(0x002074), RUNE_C(0x00207E)},
	{RUNE_C(0x002080), RUNE_C(0x00208E)},
	{RUNE_C(0x002202), RUNE_C(0x002202)},
	{RUNE_C(0x002207), RUNE_C(0x002207)},
	{RUNE_C(0x00221E), RUNE_C(0x00221E)},
	{RUNE_C(0x01D6C1), RUNE_C(0x01D6C1)},
	{RUNE_C(0x01D6DB), RUNE_C(0x01D6DB)},
	{RUNE_C(0x01D6FB), RUNE_C(0x01D6FB)},
	{RUNE_C(0x01D715), RUNE_C(0x01D715)},
	{RUNE_C(0x01D735), RUNE_C(0x01D735)},
	{RUNE_C(0x01D74F), RUNE_C(0x01D74F)},
	{RUNE_C(0x01D76F), RUNE_C(0x01D76F)},
	{RUNE_C(0x01D789), RUNE_C(0x01D789)},
	{RUNE_C(0x01D7A9), RUNE_C(0x01D7A9)},
	{RUNE_C(0x01D7C3), RUNE_C(0x01D7C3)},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rprop_is_id_compat_math_continue(rune ch)
{
	return ch <= LATIN1_MAX ? BSCHK(bitset, ch) : lookup(ch);
}
