/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"
#include "rune.h"

#include "internal/bitset.h"

/* clang-format off */

static const uint64_t bitset[] = {
	UINT64_C(0x03FF040800000000),
	UINT64_C(0x0000000000000000),
	UINT64_C(0x0000000000000000),
	UINT64_C(0x0000000000000000),
};

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{RUNE_C(0x00200D), RUNE_C(0x00200D)},
	{RUNE_C(0x0020E3), RUNE_C(0x0020E3)},
	{RUNE_C(0x00FE0F), RUNE_C(0x00FE0F)},
	{RUNE_C(0x01F1E6), RUNE_C(0x01F1FF)},
	{RUNE_C(0x01F3FB), RUNE_C(0x01F3FF)},
	{RUNE_C(0x01F9B0), RUNE_C(0x01F9B3)},
	{RUNE_C(0x0E0020), RUNE_C(0x0E007F)},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rprop_is_ecomp(rune ch)
{
	return ch <= LATIN1_MAX ? BSCHK(bitset, ch) : lookup(ch);
}
