/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"
#include "rune.h"

#include "internal/bitset.h"
#include "internal/common.h"

/* clang-format off */

static const uint64_t bitset[] = {
	UINT64_C(0x0000008400000000),
	UINT64_C(0x0000000000000000),
	UINT64_C(0x0800080000000000),
	UINT64_C(0x0000000000000000),
};

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{RUNE_C(0x002018), RUNE_C(0x00201F)},
	{RUNE_C(0x002039), RUNE_C(0x00203A)},
	{RUNE_C(0x002E42), RUNE_C(0x002E42)},
	{RUNE_C(0x00300C), RUNE_C(0x00300F)},
	{RUNE_C(0x00301D), RUNE_C(0x00301F)},
	{RUNE_C(0x00FE41), RUNE_C(0x00FE44)},
	{RUNE_C(0x00FF02), RUNE_C(0x00FF02)},
	{RUNE_C(0x00FF07), RUNE_C(0x00FF07)},
	{RUNE_C(0x00FF62), RUNE_C(0x00FF63)},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rprop_is_qmark(rune ch)
{
	return ch <= LATIN1_MAX ? BSCHK(bitset, ch) : lookup(ch);
}
