/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"

#include "internal/common.h"

/* clang-format off */

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{0x000600, 0x000605},
	{0x0006DD, 0x0006DD},
	{0x00070F, 0x00070F},
	{0x000890, 0x000891},
	{0x0008E2, 0x0008E2},
	{0x0110BD, 0x0110BD},
	{0x0110CD, 0x0110CD},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rprop_prepended_concatenation_mark(rune ch)
{
	return lookup(ch);
}
