/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"
#include "rune.h"

#include "internal/bitset.h"
#include "internal/common.h"

/* clang-format off */

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{RUNE_C(0x002E80), RUNE_C(0x002E99)},
	{RUNE_C(0x002E9B), RUNE_C(0x002EF3)},
	{RUNE_C(0x002F00), RUNE_C(0x002FD5)},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rprop_is_radical(rune ch)
{
	return lookup(ch);
}
