/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"
#include "rune.h"

#include "internal/common.h"

/* clang-format off */

#if BIT_LOOKUP
static const unsigned _BitInt(LATIN1_MAX + 1) mask =
	0x0000000000000000020C00000000000000000000000000000000000000000000uwb;
#endif

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{RUNE_C(0x0000B2), RUNE_C(0x0000B3)},
	{RUNE_C(0x0000B9), RUNE_C(0x0000B9)},
	{RUNE_C(0x002070), RUNE_C(0x002070)},
	{RUNE_C(0x002074), RUNE_C(0x00207E)},
	{RUNE_C(0x002080), RUNE_C(0x00208E)},
	{RUNE_C(0x002202), RUNE_C(0x002202)},
	{RUNE_C(0x002207), RUNE_C(0x002207)},
	{RUNE_C(0x00221E), RUNE_C(0x00221E)},
	{RUNE_C(0x01D6C1), RUNE_C(0x01D6C1)},
	{RUNE_C(0x01D6DB), RUNE_C(0x01D6DB)},
	{RUNE_C(0x01D6FB), RUNE_C(0x01D6FB)},
	{RUNE_C(0x01D715), RUNE_C(0x01D715)},
	{RUNE_C(0x01D735), RUNE_C(0x01D735)},
	{RUNE_C(0x01D74F), RUNE_C(0x01D74F)},
	{RUNE_C(0x01D76F), RUNE_C(0x01D76F)},
	{RUNE_C(0x01D789), RUNE_C(0x01D789)},
	{RUNE_C(0x01D7A9), RUNE_C(0x01D7A9)},
	{RUNE_C(0x01D7C3), RUNE_C(0x01D7C3)},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rprop_is_id_compat_math_continue(rune ch)
{
	return
#if BIT_LOOKUP
		ch <= LATIN1_MAX ? (mask & (1 << ch)) :
#endif
		lookup(ch);
}
