/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"
#include "rune.h"

#include "internal/bitset.h"

/* clang-format off */

static const uint64_t bitset[] = {
	UINT64_C(0x0000000000000000),
	UINT64_C(0x0000060000000000),
	UINT64_C(0x0000000000000000),
	UINT64_C(0x0000000000000000),
};

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{RUNE_C(0x00012F), RUNE_C(0x00012F)},
	{RUNE_C(0x000249), RUNE_C(0x000249)},
	{RUNE_C(0x000268), RUNE_C(0x000268)},
	{RUNE_C(0x00029D), RUNE_C(0x00029D)},
	{RUNE_C(0x0002B2), RUNE_C(0x0002B2)},
	{RUNE_C(0x0003F3), RUNE_C(0x0003F3)},
	{RUNE_C(0x000456), RUNE_C(0x000456)},
	{RUNE_C(0x000458), RUNE_C(0x000458)},
	{RUNE_C(0x001D62), RUNE_C(0x001D62)},
	{RUNE_C(0x001D96), RUNE_C(0x001D96)},
	{RUNE_C(0x001DA4), RUNE_C(0x001DA4)},
	{RUNE_C(0x001DA8), RUNE_C(0x001DA8)},
	{RUNE_C(0x001E2D), RUNE_C(0x001E2D)},
	{RUNE_C(0x001ECB), RUNE_C(0x001ECB)},
	{RUNE_C(0x002071), RUNE_C(0x002071)},
	{RUNE_C(0x002148), RUNE_C(0x002149)},
	{RUNE_C(0x002C7C), RUNE_C(0x002C7C)},
	{RUNE_C(0x01D422), RUNE_C(0x01D423)},
	{RUNE_C(0x01D456), RUNE_C(0x01D457)},
	{RUNE_C(0x01D48A), RUNE_C(0x01D48B)},
	{RUNE_C(0x01D4BE), RUNE_C(0x01D4BF)},
	{RUNE_C(0x01D4F2), RUNE_C(0x01D4F3)},
	{RUNE_C(0x01D526), RUNE_C(0x01D527)},
	{RUNE_C(0x01D55A), RUNE_C(0x01D55B)},
	{RUNE_C(0x01D58E), RUNE_C(0x01D58F)},
	{RUNE_C(0x01D5C2), RUNE_C(0x01D5C3)},
	{RUNE_C(0x01D5F6), RUNE_C(0x01D5F7)},
	{RUNE_C(0x01D62A), RUNE_C(0x01D62B)},
	{RUNE_C(0x01D65E), RUNE_C(0x01D65F)},
	{RUNE_C(0x01D692), RUNE_C(0x01D693)},
	{RUNE_C(0x01DF1A), RUNE_C(0x01DF1A)},
	{RUNE_C(0x01E04C), RUNE_C(0x01E04D)},
	{RUNE_C(0x01E068), RUNE_C(0x01E068)},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rprop_is_sd(rune ch)
{
	return ch <= LATIN1_MAX ? BSCHK(bitset, ch) : lookup(ch);
}
