/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"

#include "internal/common.h"

#if BIT_LOOKUP
static const unsigned _BitInt(LATIN1_MAX + 1) mask = 0x0uwb;
#endif

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{0x000149, 0x000149},
	{0x000673, 0x000673},
	{0x000F77, 0x000F77},
	{0x000F79, 0x000F79},
	{0x0017A3, 0x0017A4},
	{0x00206A, 0x00206F},
	{0x002329, 0x00232A},
	{0x0E0001, 0x0E0001},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rune_has_prop_deprecated(rune ch)
{
	return
#if BIT_LOOKUP
		ch <= LATIN1_MAX ? (mask & ch) :
#endif
		lookup(ch);
}
