/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"

#include "internal/common.h"

#if BIT_LOOKUP
static const unsigned _BitInt(LATIN1_MAX + 1) mask = 0x200000000000uwb;
#endif

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{0x00002D, 0x00002D},
	{0x00058A, 0x00058A},
	{0x0005BE, 0x0005BE},
	{0x001400, 0x001400},
	{0x001806, 0x001806},
	{0x002010, 0x002015},
	{0x002053, 0x002053},
	{0x00207B, 0x00207B},
	{0x00208B, 0x00208B},
	{0x002212, 0x002212},
	{0x002E17, 0x002E17},
	{0x002E1A, 0x002E1A},
	{0x002E3A, 0x002E3B},
	{0x002E40, 0x002E40},
	{0x002E5D, 0x002E5D},
	{0x00301C, 0x00301C},
	{0x003030, 0x003030},
	{0x0030A0, 0x0030A0},
	{0x00FE31, 0x00FE32},
	{0x00FE58, 0x00FE58},
	{0x00FE63, 0x00FE63},
	{0x00FF0D, 0x00FF0D},
	{0x010EAD, 0x010EAD},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rune_has_prop_dash(rune ch)
{
	return
#if BIT_LOOKUP
		ch <= LATIN1_MAX ? (mask & ch) :
#endif
		lookup(ch);
}
