/* This file is autogenerated by gen/rtype-prop; DO NOT EDIT. */

#include "rtype.h"

#include "internal/common.h"

#if BIT_LOOKUP
static const unsigned _BitInt(LATIN1_MAX + 1) mask = 0x0uwb;
#endif

static const struct {
	rune lo, hi;
} lookup_tbl[] = {
	{0x003006, 0x003007},
	{0x003021, 0x003029},
	{0x003038, 0x00303A},
	{0x003400, 0x004DBF},
	{0x004E00, 0x009FFF},
	{0x00F900, 0x00FA6D},
	{0x00FA70, 0x00FAD9},
	{0x016FE4, 0x016FE4},
	{0x017000, 0x0187F7},
	{0x018800, 0x018CD5},
	{0x018D00, 0x018D08},
	{0x01B170, 0x01B2FB},
	{0x020000, 0x02A6DF},
	{0x02A700, 0x02B739},
	{0x02B740, 0x02B81D},
	{0x02B820, 0x02CEA1},
	{0x02CEB0, 0x02EBE0},
	{0x02EBF0, 0x02EE5D},
	{0x02F800, 0x02FA1D},
	{0x030000, 0x03134A},
	{0x031350, 0x0323AF},
};

#define TYPE      bool
#define TABLE     lookup_tbl
#define DEFAULT   false
#define HAS_VALUE 0
#include "internal/rtype/lookup-func.h"

bool
rune_has_prop_ideographic(rune ch)
{
	return
#if BIT_LOOKUP
		ch <= LATIN1_MAX ? (mask & ch) :
#endif
		lookup(ch);
}
