#ifndef RUNE_RTYPE_H
#define RUNE_RTYPE_H

#include <stdint.h>

#include "internal/types.h"

/* clang-format off */
enum [[clang::flag_enum]] general_category : uint_fast32_t {
	GC_CN = 0,                 /* Not Assigned */
	GC_CC = UINT32_C(1) <<  0, /* Control */
	GC_CF = UINT32_C(1) <<  1, /* Format */
	GC_CO = UINT32_C(1) <<  2, /* Private Use */
	GC_CS = UINT32_C(1) <<  3, /* Surrogate */
	GC_LL = UINT32_C(1) <<  4, /* Lowercase Letter */
	GC_LM = UINT32_C(1) <<  5, /* Modifier Letter */
	GC_LO = UINT32_C(1) <<  6, /* Other Letter */
	GC_LT = UINT32_C(1) <<  7, /* Titlecase Letter */
	GC_LU = UINT32_C(1) <<  8, /* Uppercase Letter */
	GC_MC = UINT32_C(1) <<  9, /* Spacing Mark */
	GC_ME = UINT32_C(1) << 10, /* Enclosing Mark */
	GC_MN = UINT32_C(1) << 11, /* Nonspacing Mark */
	GC_ND = UINT32_C(1) << 12, /* Decimal Number */
	GC_NL = UINT32_C(1) << 13, /* Letter Number */
	GC_NO = UINT32_C(1) << 14, /* Other Number */
	GC_PC = UINT32_C(1) << 15, /* Connector Punctuation */
	GC_PD = UINT32_C(1) << 16, /* Dash Punctuation */
	GC_PE = UINT32_C(1) << 17, /* Close Punctuation */
	GC_PF = UINT32_C(1) << 18, /* Final Punctuation */
	GC_PI = UINT32_C(1) << 19, /* Initial Punctuation */
	GC_PO = UINT32_C(1) << 20, /* Other Punctuation */
	GC_PS = UINT32_C(1) << 21, /* Open Punctuation */
	GC_SC = UINT32_C(1) << 22, /* Currency Symbol */
	GC_SK = UINT32_C(1) << 23, /* Modifier Symbol */
	GC_SM = UINT32_C(1) << 24, /* Math Symbol */
	GC_SO = UINT32_C(1) << 25, /* Other Symbol */
	GC_ZL = UINT32_C(1) << 26, /* Line Separator */
	GC_ZP = UINT32_C(1) << 27, /* Paragraph Separator */
	GC_ZS = UINT32_C(1) << 28, /* Space Separator */

	GC_C  = GC_CC | GC_CF | GC_CN | GC_CO | GC_CS, /* Other */
	GC_L  = GC_LL | GC_LM | GC_LO | GC_LT | GC_LU, /* Letter */
	GC_LC = GC_LU | GC_LL | GC_LT,                 /* Cased Letter */
	GC_M  = GC_MC | GC_ME | GC_MN,                 /* Mark */
	GC_N  = GC_ND | GC_NL | GC_NO,                 /* Number */
	GC_P  = GC_PC | GC_PD | GC_PE | GC_PF | GC_PI  /* Punctuation */
	      | GC_PO | GC_PS,
	GC_S  = GC_SC | GC_SK | GC_SM | GC_SO,         /* Symbol */
	GC_Z  = GC_ZL | GC_ZP | GC_ZS,                 /* Separator */
};

enum [[clang::flag_enum]] joining_type {
	JT_U = 0,      /* Non Joining */
	JT_C = 1 << 0, /* Join Causing */
	JT_D = 1 << 1, /* Dual Joining */
	JT_R = 1 << 3, /* Right Joining */
	JT_L = 1 << 2, /* Left Joining */
	JT_T = 1 << 4, /* Transparent */
};
/* clang-format on */

[[unsequenced]] bool riscntrl(rune);
[[unsequenced]] bool risdigit(rune);
[[unsequenced]] bool risgraph(rune);
[[unsequenced]] bool rislower(rune);
[[unsequenced]] bool rismark(rune);
[[unsequenced]] bool risnumber(rune);
[[unsequenced]] bool rispunct(rune);
[[unsequenced]] bool risspace(rune);
[[unsequenced]] bool rissymbol(rune);
[[unsequenced]] bool ristitle(rune);
[[unsequenced]] bool risupper(rune);

[[unsequenced]] enum general_category rprop_get_general_category(rune);
[[unsequenced]] enum joining_type rprop_get_joining_type(rune);

/* Non-autogenerated rprop_is_*() functions */
[[unsequenced]] bool rprop_is_ascii_hex_digit(rune);
[[unsequenced]] bool rprop_is_ids_trinary_operator(rune);
[[unsequenced]] bool rprop_is_ids_unary_operator(rune);
[[unsequenced]] bool rprop_is_join_control(rune);
[[unsequenced]] bool rprop_is_noncharacter_code_point(rune);
[[unsequenced]] bool rprop_is_pattern_white_space(rune);

/* PROP PREDICATES START */
[[unsequenced]] bool rprop_is_alphabetic(rune);
[[unsequenced]] bool rprop_is_bidi_control(rune);
[[unsequenced]] bool rprop_is_case_ignorable(rune);
[[unsequenced]] bool rprop_is_cased(rune);
[[unsequenced]] bool rprop_is_changes_when_casefolded(rune);
[[unsequenced]] bool rprop_is_changes_when_casemapped(rune);
[[unsequenced]] bool rprop_is_changes_when_lowercased(rune);
[[unsequenced]] bool rprop_is_changes_when_nfkc_casefolded(rune);
[[unsequenced]] bool rprop_is_changes_when_titlecased(rune);
[[unsequenced]] bool rprop_is_changes_when_uppercased(rune);
[[unsequenced]] bool rprop_is_dash(rune);
[[unsequenced]] bool rprop_is_default_ignorable_code_point(rune);
[[unsequenced]] bool rprop_is_deprecated(rune);
[[unsequenced]] bool rprop_is_diacritic(rune);
[[unsequenced]] bool rprop_is_emoji(rune);
[[unsequenced]] bool rprop_is_emoji_component(rune);
[[unsequenced]] bool rprop_is_emoji_modifier(rune);
[[unsequenced]] bool rprop_is_emoji_modifier_base(rune);
[[unsequenced]] bool rprop_is_emoji_presentation(rune);
[[unsequenced]] bool rprop_is_extended_pictographic(rune);
[[unsequenced]] bool rprop_is_extender(rune);
[[unsequenced]] bool rprop_is_grapheme_base(rune);
[[unsequenced]] bool rprop_is_grapheme_extend(rune);
[[unsequenced]] bool rprop_is_hex_digit(rune);
[[unsequenced]] bool rprop_is_id_compat_math_continue(rune);
[[unsequenced]] bool rprop_is_id_compat_math_start(rune);
[[unsequenced]] bool rprop_is_id_continue(rune);
[[unsequenced]] bool rprop_is_id_start(rune);
[[unsequenced]] bool rprop_is_ideographic(rune);
[[unsequenced]] bool rprop_is_ids_binary_operator(rune);
[[unsequenced]] bool rprop_is_indic_conjunct_break(rune);
[[unsequenced]] bool rprop_is_logical_order_exception(rune);
[[unsequenced]] bool rprop_is_lowercase(rune);
[[unsequenced]] bool rprop_is_math(rune);
[[unsequenced]] bool rprop_is_pattern_syntax(rune);
[[unsequenced]] bool rprop_is_prepended_concatenation_mark(rune);
[[unsequenced]] bool rprop_is_quotation_mark(rune);
[[unsequenced]] bool rprop_is_radical(rune);
[[unsequenced]] bool rprop_is_regional_indicator(rune);
[[unsequenced]] bool rprop_is_sentence_terminal(rune);
[[unsequenced]] bool rprop_is_soft_dotted(rune);
[[unsequenced]] bool rprop_is_terminal_punctuation(rune);
[[unsequenced]] bool rprop_is_unified_ideograph(rune);
[[unsequenced]] bool rprop_is_uppercase(rune);
[[unsequenced]] bool rprop_is_variation_selector(rune);
[[unsequenced]] bool rprop_is_white_space(rune);
[[unsequenced]] bool rprop_is_xid_continue(rune);
[[unsequenced]] bool rprop_is_xid_start(rune);
/* PROP PREDICATES END */

#endif
