/* This file is autogenerated by gen/rtype-suc; DO NOT EDIT. */

#ifndef RUNE_INTERNAL_RTYPE_SUC_H
#define RUNE_INTERNAL_RTYPE_SUC_H

/* IWYU pragma: private */
/* clang-format off */

#include "../types.h"
#include "../../rtype.h"
#include "../../rune.h"

static const struct {
	rune key, val;
} rtype_suc_tbl[] = {
};

#endif /* !RUNE_INTERNAL_RTYPE_SUC_H */
